import { randomUUID } from "node:crypto";
import { datetime, varchar } from "drizzle-orm/mysql-core";

/**
 * The column conventions every table follows, declared once.
 *
 * MySQL forces three decisions that Postgres did not, and making each of them
 * in one place is what stops twelve tables from drifting apart:
 *
 * **Lengths.** `text` cannot be indexed in MySQL without a prefix length, and
 * a key column in `utf8mb4` is capped at 3072 bytes — 768 characters. Every
 * column that is a key, a foreign key or part of an index is therefore a
 * `varchar` with a stated length, and `ID_LENGTH` is the one all of them share
 * so a foreign key can never fail to match its target's type.
 *
 * **Time.** `TIMESTAMP` in MySQL dies in 2038, so timestamps are `DATETIME(3)`
 * — millisecond precision, no upper bound. `DATETIME` carries no zone, which
 * is safe only because `src/db/index.ts` pins both the driver and the session
 * to UTC. That pinning and this type are one decision in two files.
 *
 * **Defaults.** `now()` as a column default needs MySQL 8.0.13+ and behaves
 * differently on MariaDB, so "now" is produced by the driver instead. One
 * clock, and the DDL stays portable across whatever the host actually runs.
 */

/** Wide enough for both a UUID (36) and a Better Auth id (32). */
export const ID_LENGTH = 64;

/** Primary key: a string id, generated by the application. */
export const id = () =>
  varchar({ length: ID_LENGTH })
    .primaryKey()
    .$defaultFn(() => randomUUID());

/** A reference column, typed to match `id()` exactly. */
export const ref = () => varchar({ length: ID_LENGTH });

/** A nullable point in time, UTC. */
export const ts = () => datetime({ mode: "date", fsp: 3 });

/** A required point in time, defaulting to now, UTC. */
export const tsNow = () =>
  datetime({ mode: "date", fsp: 3 })
    .notNull()
    .$defaultFn(() => new Date());
